version: '3'

services:
  mongodb:
    image: mongo # This is name of the mongodb docker image from dockerhub
    container_name: mongodb # This is the name of our container
    restart: unless-stopped # Use this if you want the container to autorestart both on boot up and on failure
    command: mongod --auth --logpath /var/log/mongodb/mongod.log --logappend # --auth tells mongodb to enable authentication
    environment:
      MONGODB_DATA_DIR: /data/db # Path to store data for all collections and dbs
      # MONGODB_LOGFILE: /var/log/mongodb/mongod.log
    ports:
      - 27017:27017 # Default mongodb port
    volumes:
      - $HOME/mongodb:/data/db # Mapping the /data/db path inside the container to a custom directory in the host pc (pc where this container is running)
      - $HOME/log/mongodb/:/var/log/mongodb/ # Mapping the logs from the container to a file in the host pc
    networks:
      - mongodb-network # Any container attached to this network can communicate with this container by its container name

networks:
  mongodb-network:
      
